### ISSUE TITLE
Migrate API definitions from OpenApi 3.0 to 3.1

### ISSUE THREAD

**Issue by swilczynski** [Rebilly/api-definitions#1648]

**Comment by adamaltman** [comment]
After we're on 3.1.

Change to this:

```yaml
id:
  $ref: ./id.yaml
  description: Adam foo bar ID.
```

From this:

```yaml
id:
  allOf:
    - $ref: ./id.yaml
    - description: Adam foo bar ID.
```
